/**
 * All 237 city URL paths used for sitemap generation, generateStaticParams, etc.
 * Extracted from public/city-urls.json for easy TS import.
 */
export const CITY_PATHS: Array<{ country: string; region: string; city: string }> = [
  // ---- Europe: Austria ----
  { country: "at", region: "vie", city: "vienna" },
  { country: "at", region: "vie", city: "graz" },
  { country: "at", region: "vie", city: "linz" },
  { country: "at", region: "vie", city: "salzburg" },
  { country: "at", region: "vie", city: "innsbruck" },
  // ---- Europe: Switzerland ----
  { country: "ch", region: "zh", city: "zurich" },
  { country: "ch", region: "zh", city: "geneva" },
  { country: "ch", region: "zh", city: "basel" },
  { country: "ch", region: "zh", city: "lausanne" },
  { country: "ch", region: "zh", city: "bern" },
  // ---- Europe: Germany ----
  { country: "de", region: "by", city: "berlin" },
  { country: "de", region: "by", city: "munich" },
  { country: "de", region: "by", city: "hamburg" },
  { country: "de", region: "by", city: "frankfurt" },
  { country: "de", region: "by", city: "cologne" },
  { country: "de", region: "by", city: "stuttgart" },
  { country: "de", region: "by", city: "dusseldorf" },
  { country: "de", region: "by", city: "dresden" },
  { country: "de", region: "by", city: "leipzig" },
  { country: "de", region: "by", city: "nuremberg" },
  // ---- Europe: Czech Republic ----
  { country: "cz", region: "pr", city: "prague" },
  { country: "cz", region: "pr", city: "brno" },
  { country: "cz", region: "pr", city: "ostrava" },
  // ---- Europe: Denmark ----
  { country: "dk", region: "84", city: "copenhagen" },
  { country: "dk", region: "84", city: "aarhus" },
  { country: "dk", region: "84", city: "odense" },
  // ---- Europe: Estonia ----
  { country: "ee", region: "37", city: "tallinn" },
  { country: "ee", region: "37", city: "tartu" },
  // ---- Europe: Finland ----
  { country: "fi", region: "18", city: "helsinki" },
  { country: "fi", region: "18", city: "tampere" },
  { country: "fi", region: "18", city: "turku" },
  // ---- Europe: Greece ----
  { country: "gr", region: "a1", city: "athens" },
  { country: "gr", region: "a1", city: "thessaloniki" },
  { country: "gr", region: "a1", city: "patras" },
  // ---- Europe: Hungary ----
  { country: "hu", region: "bu", city: "budapest" },
  { country: "hu", region: "bu", city: "szeged" },
  { country: "hu", region: "bu", city: "debrecen" },
  // ---- Europe: Ireland ----
  { country: "ie", region: "d", city: "dublin" },
  { country: "ie", region: "d", city: "cork" },
  { country: "ie", region: "d", city: "galway" },
  // ---- Europe: Luxembourg ----
  { country: "lu", region: "lx", city: "luxembourg-city" },
  { country: "lu", region: "lx", city: "esch" },
  // ---- Europe: Latvia ----
  { country: "lv", region: "ri", city: "riga" },
  { country: "lv", region: "ri", city: "daugavpils" },
  // ---- Europe: Spain ----
  { country: "es", region: "md", city: "madrid" },
  { country: "es", region: "md", city: "barcelona" },
  { country: "es", region: "md", city: "valencia" },
  { country: "es", region: "md", city: "seville" },
  { country: "es", region: "md", city: "bilbao" },
  // ---- Europe: Italy ----
  { country: "it", region: "la", city: "rome" },
  { country: "it", region: "la", city: "milan" },
  { country: "it", region: "la", city: "naples" },
  { country: "it", region: "la", city: "turin" },
  { country: "it", region: "la", city: "florence" },
  // ---- Europe: Lithuania ----
  { country: "lt", region: "vl", city: "vilnius" },
  { country: "lt", region: "vl", city: "kaunas" },
  { country: "lt", region: "vl", city: "klaipeda" },
  // ---- Europe: Netherlands ----
  { country: "nl", region: "nh", city: "amsterdam" },
  { country: "nl", region: "nh", city: "rotterdam" },
  { country: "nl", region: "nh", city: "the-hague" },
  { country: "nl", region: "nh", city: "utrecht" },
  // ---- Europe: Norway ----
  { country: "no", region: "03", city: "oslo" },
  { country: "no", region: "03", city: "bergen" },
  { country: "no", region: "03", city: "trondheim" },
  // ---- Europe: Portugal ----
  { country: "pt", region: "lx", city: "lisbon" },
  { country: "pt", region: "lx", city: "porto" },
  { country: "pt", region: "lx", city: "coimbra" },
  // ---- Europe: Romania ----
  { country: "ro", region: "b", city: "bucharest" },
  { country: "ro", region: "b", city: "cluj" },
  { country: "ro", region: "b", city: "iasi" },
  // ---- Europe: Sweden ----
  { country: "se", region: "ab", city: "stockholm" },
  { country: "se", region: "ab", city: "gothenburg" },
  { country: "se", region: "ab", city: "malmo" },
  // ---- Europe: Turkey ----
  { country: "tr", region: "34", city: "istanbul" },
  { country: "tr", region: "34", city: "ankara" },
  { country: "tr", region: "34", city: "izmir" },
  // ---- Europe: Malta ----
  { country: "mt", region: "ma", city: "valletta" },
  { country: "mt", region: "ma", city: "sliema" },
  // ---- Europe: Belgium ----
  { country: "be", region: "bru", city: "brussels" },
  { country: "be", region: "bru", city: "antwerp" },
  { country: "be", region: "bru", city: "ghent" },
  // ---- Europe: France ----
  { country: "fr", region: "idf", city: "paris" },
  { country: "fr", region: "idf", city: "lyon" },
  { country: "fr", region: "idf", city: "marseille" },
  { country: "fr", region: "idf", city: "toulouse" },
  // ---- Europe: Poland ----
  { country: "pl", region: "mz", city: "warsaw" },
  { country: "pl", region: "mz", city: "krakow" },
  { country: "pl", region: "mz", city: "wroclaw" },
  // ---- Europe: United Kingdom ----
  { country: "gb", region: "ldn", city: "london" },
  { country: "gb", region: "ldn", city: "manchester" },
  { country: "gb", region: "ldn", city: "birmingham" },
  { country: "gb", region: "ldn", city: "leeds" },
  { country: "gb", region: "ldn", city: "glasgow" },
  // ---- Europe: Others ----
  { country: "bg", region: "22", city: "sofia" },
  { country: "bg", region: "22", city: "plovdiv" },
  { country: "md", region: "chi", city: "chisinau" },
  { country: "sk", region: "bl", city: "bratislava" },
  { country: "sk", region: "bl", city: "kosice" },
  { country: "si", region: "lj", city: "ljubljana" },
  { country: "si", region: "lj", city: "maribor" },
  { country: "hr", region: "zg", city: "zagreb" },
  { country: "hr", region: "zg", city: "split" },
  { country: "rs", region: "bg", city: "belgrade" },
  { country: "rs", region: "bg", city: "novi-sad" },
  // ---- Asia: India ----
  { country: "in", region: "ts", city: "hyderabad" },
  { country: "in", region: "ts", city: "bangalore" },
  { country: "in", region: "ts", city: "mumbai" },
  { country: "in", region: "ts", city: "pune" },
  { country: "in", region: "ts", city: "chennai" },
  { country: "in", region: "ts", city: "delhi" },
  { country: "in", region: "ts", city: "kolkata" },
  { country: "in", region: "ts", city: "ahmedabad" },
  { country: "in", region: "ts", city: "jaipur" },
  { country: "in", region: "ts", city: "surat" },
  // ---- Asia: China ----
  { country: "cn", region: "bj", city: "beijing" },
  { country: "cn", region: "bj", city: "shanghai" },
  { country: "cn", region: "bj", city: "shenzhen" },
  { country: "cn", region: "bj", city: "guangzhou" },
  // ---- Asia: Others ----
  { country: "hk", region: "hk", city: "central" },
  { country: "hk", region: "hk", city: "kowloon" },
  { country: "mo", region: "mo", city: "macao" },
  { country: "tw", region: "tp", city: "taipei" },
  { country: "tw", region: "tp", city: "taichung" },
  { country: "tw", region: "tp", city: "kaohsiung" },
  { country: "jp", region: "13", city: "tokyo" },
  { country: "jp", region: "13", city: "osaka" },
  { country: "jp", region: "13", city: "yokohama" },
  // ---- Oceania ----
  { country: "au", region: "nsw", city: "sydney" },
  { country: "au", region: "nsw", city: "melbourne" },
  { country: "au", region: "nsw", city: "brisbane" },
  { country: "au", region: "nsw", city: "perth" },
  // ---- Southeast Asia ----
  { country: "my", region: "kl", city: "kuala-lumpur" },
  { country: "my", region: "kl", city: "penang" },
  { country: "my", region: "kl", city: "johor-bahru" },
  { country: "nz", region: "auk", city: "auckland" },
  { country: "nz", region: "auk", city: "wellington" },
  { country: "nz", region: "auk", city: "christchurch" },
  { country: "ph", region: "ncr", city: "manila" },
  { country: "ph", region: "ncr", city: "cebu" },
  { country: "ph", region: "ncr", city: "davao" },
  { country: "sg", region: "sg", city: "singapore" },
  { country: "th", region: "10", city: "bangkok" },
  { country: "th", region: "10", city: "chiang-mai" },
  { country: "th", region: "10", city: "phuket" },
  { country: "vn", region: "sg", city: "ho-chi-minh" },
  { country: "vn", region: "sg", city: "hanoi" },
  { country: "vn", region: "sg", city: "danang" },
  { country: "kr", region: "11", city: "seoul" },
  { country: "kr", region: "11", city: "busan" },
  { country: "kr", region: "11", city: "incheon" },
  { country: "pk", region: "sd", city: "karachi" },
  { country: "pk", region: "sd", city: "lahore" },
  { country: "pk", region: "sd", city: "islamabad" },
  { country: "lk", region: "we", city: "colombo" },
  { country: "lk", region: "we", city: "kandy" },
  { country: "id", region: "jk", city: "jakarta" },
  { country: "id", region: "jk", city: "surabaya" },
  { country: "id", region: "jk", city: "bandung" },
  { country: "kz", region: "alm", city: "almaty" },
  { country: "kz", region: "alm", city: "astana" },
  { country: "bt", region: "ty", city: "thimphu" },
  { country: "np", region: "ba", city: "kathmandu" },
  { country: "np", region: "ba", city: "pokhara" },
  { country: "uz", region: "tk", city: "tashkent" },
  { country: "uz", region: "tk", city: "samarkand" },
  // ---- Americas: Canada ----
  { country: "ca", region: "on", city: "toronto" },
  { country: "ca", region: "on", city: "vancouver" },
  { country: "ca", region: "on", city: "montreal" },
  { country: "ca", region: "on", city: "calgary" },
  { country: "ca", region: "on", city: "ottawa" },
  { country: "ca", region: "on", city: "edmonton" },
  { country: "ca", region: "on", city: "winnipeg" },
  { country: "ca", region: "on", city: "halifax" },
  { country: "ca", region: "on", city: "mississauga" },
  { country: "ca", region: "on", city: "brampton" },
  // ---- Americas: United States ----
  { country: "us", region: "ca", city: "california" },
  { country: "us", region: "ca", city: "new-york" },
  { country: "us", region: "ca", city: "chicago" },
  { country: "us", region: "ca", city: "houston" },
  { country: "us", region: "ca", city: "seattle" },
  { country: "us", region: "ca", city: "miami" },
  { country: "us", region: "ca", city: "san-francisco" },
  { country: "us", region: "ca", city: "los-angeles" },
  { country: "us", region: "ca", city: "boston" },
  { country: "us", region: "ca", city: "austin" },
  // ---- Americas: Central America ----
  { country: "cr", region: "sj", city: "san-jose" },
  { country: "gt", region: "gu", city: "guatemala-city" },
  { country: "mx", region: "cmx", city: "mexico-city" },
  { country: "mx", region: "cmx", city: "guadalajara" },
  { country: "mx", region: "cmx", city: "monterrey" },
  { country: "pa", region: "pa", city: "panama-city" },
  // ---- Americas: South America ----
  { country: "br", region: "sp", city: "sao-paulo" },
  { country: "br", region: "sp", city: "rio-de-janeiro" },
  { country: "br", region: "sp", city: "brasilia" },
  { country: "ar", region: "c", city: "buenos-aires" },
  { country: "ar", region: "c", city: "cordoba" },
  { country: "ar", region: "c", city: "rosario" },
  { country: "cl", region: "rm", city: "santiago" },
  { country: "cl", region: "rm", city: "valparaiso" },
  { country: "ec", region: "p", city: "quito" },
  { country: "ec", region: "p", city: "guayaquil" },
  { country: "co", region: "dc", city: "bogota" },
  { country: "co", region: "dc", city: "medellin" },
  { country: "co", region: "dc", city: "cali" },
  { country: "pe", region: "li", city: "lima" },
  { country: "pe", region: "li", city: "arequipa" },
  { country: "uy", region: "mo", city: "montevideo" },
  { country: "ve", region: "dc", city: "caracas" },
  { country: "ve", region: "dc", city: "maracaibo" },
  { country: "bo", region: "lp", city: "la-paz" },
  { country: "bo", region: "lp", city: "santa-cruz" },
  // ---- Middle East & Africa ----
  { country: "ae", region: "du", city: "dubai" },
  { country: "ae", region: "du", city: "abu-dhabi" },
  { country: "ae", region: "du", city: "sharjah" },
  { country: "qa", region: "da", city: "doha" },
  { country: "eg", region: "c", city: "cairo" },
  { country: "eg", region: "c", city: "alexandria" },
  { country: "sa", region: "01", city: "riyadh" },
  { country: "sa", region: "01", city: "jeddah" },
  { country: "sa", region: "01", city: "dammam" },
  { country: "za", region: "gt", city: "johannesburg" },
  { country: "za", region: "gt", city: "cape-town" },
  { country: "za", region: "gt", city: "durban" },
  { country: "ma", region: "cas", city: "casablanca" },
  { country: "ma", region: "cas", city: "rabat" },
  { country: "ma", region: "cas", city: "marrakesh" },
  { country: "tn", region: "tn", city: "tunis" },
  { country: "tn", region: "tn", city: "sfax" },
  { country: "kw", region: "kw", city: "kuwait-city" },
  { country: "om", region: "mu", city: "muscat" },
  { country: "om", region: "mu", city: "salalah" },
  { country: "ke", region: "na", city: "nairobi" },
  { country: "ke", region: "na", city: "mombasa" },
  { country: "ng", region: "la", city: "lagos" },
  { country: "ng", region: "la", city: "abuja" },
  { country: "ng", region: "la", city: "ibadan" },
  { country: "bw", region: "ga", city: "gaborone" },
];
