const fs = require('fs');
const path = require('path');

const languages = ['ar', 'de', 'es', 'fr', 'ja', 'ko', 'pt', 'tr', 'zh'];

const translations = {
  ar: {
    loading: "جاري تحميل الدورة...",
    notFound: "الدورة غير موجودة",
    home: "الرئيسية",
    training: "التدريب",
    trainingInCity: "التدريب في {{cityTitle}}",
    ratings: "تقييمات",
    hoursTotal: "{{hours}} ساعة إجمالاً",
    lessons: "دروس",
    maxStudents: "الحد الأقصى {{count}}",
    downloadBrochure: "تحميل الكتيب",
    whatYouWillLearn: "ماذا ستتعلم",
    courseIncludes: "تتضمن هذه الدورة:",
    onDemandVideo: "{{hours}} ساعة و {{minutes}} دقيقة فيديو حسب الطلب",
    handsOnExercises: "تمارين عملية",
    certificateOfCompletion: "شهادة إتمام",
    fullLifetimeAccess: "وصول كامل مدى الحياة",
    accessOnMobile: "الوصول عبر الهاتف المحمول",
    courseContent: "محتوى الدورة",
    modules: "وحدات",
    prerequisites: "المتطلبات الأساسية",
    recommendedPrerequisites: "المتطلبات الأساسية الموصى بها",
    completeBeforeStarting: "أكمل هذه الدورات قبل البدء",
    viewDetails: "عرض التفاصيل",
    description: "الوصف",
    showMore: "عرض المزيد",
    showLess: "عرض أقل",
    whyChooseThisCourse: "لماذا تختار هذه الدورة؟",
    expertInstructorsTitle: "مدربون خبراء",
    expertInstructorsDesc: "خبرة تزيد عن 10 سنوات",
    handsOnLabsTitle: "مختبرات عملية",
    handsOnLabsDesc: "مشاريع واقعية",
    certificationTitle: "شهادة",
    certificationDesc: "معترف بها في الصناعة",
    studentFeedback: "آراء الطلاب",
    showMoreReviews: "عرض المزيد من المراجعات",
    faqTitle: "الأسئلة الشائعة",
    courseFee: "رسوم الدورة",
    free: "مجاني",
    enrollNow: "سجل الآن",
    readyToMaster: "جاهز لإتقان {{courseTitle}}؟",
    readyToMasterDesc: "انضم إلى أكثر من {{count}} طالب قيموا هذه الدورة بـ {{rating}}★",
    reviews: [
      { user: "أميليا تشن", date: "منذ يومين", text: "دورة رائعة للغاية! الهيكل مثالي - كل وحدة تبني على السابقة. انتقلت من المعرفة الصفرية إلى بناء تطبيقاتي الخاصة في 6 أسابيع." },
      { user: "رافي باتيل", date: "منذ أسبوع", text: "أفضل دورة أخذتها. وتيرة جيدة، مشاريع ممتازة. طبقت هذه المهارات بالفعل في وظيفتي وحصلت على ترقية!" },
      { user: "صوفيا رودريغيز", date: "منذ أسبوعين", text: "دورة شاملة حقاً. تغطي كل شيء من الأساسيات إلى المواضيع المتقدمة. قيمة استثنائية." },
    ],
    faqs: [
      { q: "ما هي المتطلبات التقنية؟", a: "كمبيوتر محمول أو مكتبي قياسي مع اتصال بالإنترنت. جميع الأدوات مجانية ومفتوحة المصدر." },
      { q: "هل هناك شهادة؟", a: "نعم، ستتلقى شهادة إتمام معتمدة لـ LinkedIn والسيرة الذاتية." },
      { q: "ماذا لو لم يكن لدي خبرة في البرمجة؟", a: "تم تصميم الدورة لجميع المستويات. نبدأ من الأساسيات ونبني خطوة بخطوة." },
    ]
  },
  de: {
    loading: "Kurs wird geladen...",
    notFound: "Kurs nicht gefunden",
    home: "Startseite",
    training: "Schulung",
    trainingInCity: "Schulung in {{cityTitle}}",
    ratings: "Bewertungen",
    hoursTotal: "{{hours}} Std. insgesamt",
    lessons: "Lektionen",
    maxStudents: "Max. {{count}}",
    downloadBrochure: "Broschüre herunterladen",
    whatYouWillLearn: "Was Sie lernen werden",
    courseIncludes: "Dieser Kurs beinhaltet:",
    onDemandVideo: "{{hours}} Std. {{minutes}} Min. On-Demand-Video",
    handsOnExercises: "Praktische Übungen",
    certificateOfCompletion: "Abschlusszertifikat",
    fullLifetimeAccess: "Lebenslanger Zugriff",
    accessOnMobile: "Zugriff auf dem Handy",
    courseContent: "Kursinhalt",
    modules: "Module",
    prerequisites: "Voraussetzungen",
    recommendedPrerequisites: "Empfohlene Voraussetzungen",
    completeBeforeStarting: "Schließen Sie diese Kurse ab, bevor Sie beginnen",
    viewDetails: "Details anzeigen",
    description: "Beschreibung",
    showMore: "Mehr anzeigen",
    showLess: "Weniger anzeigen",
    whyChooseThisCourse: "Warum diesen Kurs wählen?",
    expertInstructorsTitle: "Experten-Trainer",
    expertInstructorsDesc: "10+ Jahre Erfahrung",
    handsOnLabsTitle: "Praxis-Labs",
    handsOnLabsDesc: "Reale Projekte",
    certificationTitle: "Zertifizierung",
    certificationDesc: "Branchenweit anerkannt",
    studentFeedback: "Studenten-Feedback",
    showMoreReviews: "Mehr Bewertungen anzeigen",
    faqTitle: "Häufig gestellte Fragen",
    courseFee: "Kursgebühr",
    free: "Kostenlos",
    enrollNow: "Jetzt anmelden",
    readyToMaster: "Bereit, {{courseTitle}} zu meistern?",
    readyToMasterDesc: "Schließen Sie sich {{count}}+ Studenten an, die diesen Kurs mit {{rating}}★ bewertet haben",
    reviews: [
      { user: "Amelia Chen", date: "vor 2 Tagen", text: "Absolut fantastischer Kurs! Die Struktur ist perfekt – jedes Modul baut auf dem vorherigen auf. Ich bin in 6 Wochen von Nullwissen zum Erstellen eigener Anwendungen gekommen." },
      { user: "Ravi Patel", date: "vor 1 Woche", text: "Bester Kurs, den ich je belegt habe. Gutes Tempo, ausgezeichnete Projekte. Habe diese Fähigkeiten bereits in meinem Job angewendet und wurde befördert!" },
      { user: "Sofia Rodriguez", date: "vor 2 Wochen", text: "Wirklich umfassender Kurs. Deckt alles ab, von den Grundlagen bis zu fortgeschrittenen Themen. Außergewöhnlicher Wert." },
    ],
    faqs: [
      { q: "Was sind die technischen Voraussetzungen?", a: "Ein Standard-Laptop oder -Desktop mit Internetverbindung. Alle Tools sind kostenlos und Open Source." },
      { q: "Gibt es ein Zertifikat?", a: "Ja, Sie erhalten ein verifiziertes Abschlusszertifikat für LinkedIn und Ihren Lebenslauf." },
      { q: "Was ist, wenn ich keine Programmiererfahrung habe?", a: "Der Kurs ist für alle Niveaus konzipiert. Wir beginnen bei den Grundlagen und bauen Schritt für Schritt darauf auf." },
    ]
  },
  es: {
    loading: "Cargando curso...",
    notFound: "Curso no encontrado",
    home: "Inicio",
    training: "Capacitación",
    trainingInCity: "Capacitación en {{cityTitle}}",
    ratings: "calificaciones",
    hoursTotal: "{{hours}}h en total",
    lessons: "lecciones",
    maxStudents: "Máx. {{count}}",
    downloadBrochure: "Descargar folleto",
    whatYouWillLearn: "Lo que aprenderás",
    courseIncludes: "Este curso incluye:",
    onDemandVideo: "{{hours}}h {{minutes}}m de video bajo demanda",
    handsOnExercises: "Ejercicios prácticos",
    certificateOfCompletion: "Certificado de finalización",
    fullLifetimeAccess: "Acceso de por vida",
    accessOnMobile: "Acceso en móvil",
    courseContent: "Contenido del curso",
    modules: "módulos",
    prerequisites: "Requisitos previos",
    recommendedPrerequisites: "Requisitos recomendados",
    completeBeforeStarting: "Completa estos cursos antes de comenzar",
    viewDetails: "Ver detalles",
    description: "Descripción",
    showMore: "Mostrar más",
    showLess: "Mostrar menos",
    whyChooseThisCourse: "¿Por qué elegir este curso?",
    expertInstructorsTitle: "Instructores expertos",
    expertInstructorsDesc: "Más de 10 años de experiencia",
    handsOnLabsTitle: "Laboratorios prácticos",
    handsOnLabsDesc: "Proyectos reales",
    certificationTitle: "Certificación",
    certificationDesc: "Reconocida por la industria",
    studentFeedback: "Comentarios de los estudiantes",
    showMoreReviews: "Mostrar más reseñas",
    faqTitle: "Preguntas frecuentes",
    courseFee: "Tarifa del curso",
    free: "Gratis",
    enrollNow: "Inscribirse ahora",
    readyToMaster: "¿Listo para dominar {{courseTitle}}?",
    readyToMasterDesc: "Únete a más de {{count}} estudiantes que calificaron este curso con {{rating}}★",
    reviews: [
      { user: "Amelia Chen", date: "hace 2 días", text: "¡Curso absolutamente fantástico! La estructura es perfecta: cada módulo se basa en el anterior. Pasé de cero conocimientos a crear mis propias aplicaciones en 6 semanas." },
      { user: "Ravi Patel", date: "hace 1 semana", text: "El mejor curso que he tomado. Buen ritmo, excelentes proyectos. ¡Ya apliqué estas habilidades en mi trabajo y obtuve un ascenso!" },
      { user: "Sofia Rodriguez", date: "hace 2 semanas", text: "Curso realmente completo. Cubre todo, desde lo básico hasta temas avanzados. Valor excepcional." },
    ],
    faqs: [
      { q: "¿Cuáles son los requisitos técnicos?", a: "Una computadora portátil o de escritorio estándar con conexión a Internet. Todas las herramientas son gratuitas y de código abierto." },
      { q: "¿Hay un certificado?", a: "Sí, recibirás un certificado de finalización verificado para LinkedIn y currículum." },
      { q: "¿Qué pasa si no tengo experiencia en programación?", a: "El curso está diseñado para todos los niveles. Comenzamos desde los fundamentos y avanzamos paso a paso." },
    ]
  },
  fr: {
    loading: "Chargement du cours...",
    notFound: "Cours non trouvé",
    home: "Accueil",
    training: "Formation",
    trainingInCity: "Formation à {{cityTitle}}",
    ratings: "avis",
    hoursTotal: "{{hours}}h au total",
    lessons: "leçons",
    maxStudents: "Max {{count}}",
    downloadBrochure: "Télécharger la brochure",
    whatYouWillLearn: "Ce que vous apprendrez",
    courseIncludes: "Ce cours comprend :",
    onDemandVideo: "{{hours}}h {{minutes}}m de vidéo à la demande",
    handsOnExercises: "Exercices pratiques",
    certificateOfCompletion: "Certificat de réussite",
    fullLifetimeAccess: "Accès illimité à vie",
    accessOnMobile: "Accès sur mobile",
    courseContent: "Contenu du cours",
    modules: "modules",
    prerequisites: "Prérequis",
    recommendedPrerequisites: "Prérequis recommandés",
    completeBeforeStarting: "Complétez ces cours avant de commencer",
    viewDetails: "Voir les détails",
    description: "Description",
    showMore: "Afficher plus",
    showLess: "Afficher moins",
    whyChooseThisCourse: "Pourquoi choisir ce cours ?",
    expertInstructorsTitle: "Instructeurs experts",
    expertInstructorsDesc: "10+ ans d'expérience",
    handsOnLabsTitle: "Ateliers pratiques",
    handsOnLabsDesc: "Projets réels",
    certificationTitle: "Certification",
    certificationDesc: "Reconnue par l'industrie",
    studentFeedback: "Avis des étudiants",
    showMoreReviews: "Afficher plus d'avis",
    faqTitle: "Questions fréquemment posées",
    courseFee: "Frais de cours",
    free: "Gratuit",
    enrollNow: "S'inscrire maintenant",
    readyToMaster: "Prêt à maîtriser {{courseTitle}} ?",
    readyToMasterDesc: "Rejoignez {{count}}+ étudiants qui ont noté ce cours {{rating}}★",
    reviews: [
      { user: "Amelia Chen", date: "il y a 2 jours", text: "Cours absolument fantastique ! La structure est parfaite — chaque module s'appuie sur le précédent. Je suis passée de zéro connaissance à la création de mes propres applications en 6 semaines." },
      { user: "Ravi Patel", date: "il y a 1 semaine", text: "Le meilleur cours que j'ai suivi. Bon rythme, excellents projets. J'ai déjà appliqué ces compétences dans mon travail et j'ai obtenu une promotion !" },
      { user: "Sofia Rodriguez", date: "il y a 2 semaines", text: "Cours vraiment complet. Couvre tout, des bases aux sujets avancés. Valeur exceptionnelle." },
    ],
    faqs: [
      { q: "Quelles sont les exigences techniques ?", a: "Un ordinateur portable ou de bureau standard avec une connexion Internet. Tous les outils sont gratuits et open-source." },
      { q: "Y a-t-il un certificat ?", a: "Oui, vous recevrez un certificat de réussite vérifié pour LinkedIn et votre CV." },
      { q: "Et si je n'ai pas d'expérience en programmation ?", a: "Le cours est conçu pour tous les niveaux. Nous commençons par les bases et construisons étape par étape." },
    ]
  },
  ja: {
    loading: "コースを読み込み中...",
    notFound: "コースが見つかりません",
    home: "ホーム",
    training: "トレーニング",
    trainingInCity: "{{cityTitle}}でのトレーニング",
    ratings: "件の評価",
    hoursTotal: "合計 {{hours}} 時間",
    lessons: "レッスン",
    maxStudents: "最大 {{count}} 名",
    downloadBrochure: "パンフレットをダウンロード",
    whatYouWillLearn: "学習内容",
    courseIncludes: "このコースに含まれるもの：",
    onDemandVideo: "{{hours}} 時間 {{minutes}} 分のオンデマンドビデオ",
    handsOnExercises: "実践演習",
    certificateOfCompletion: "修了証書",
    fullLifetimeAccess: "無期限アクセス",
    accessOnMobile: "モバイルでのアクセス",
    courseContent: "コース内容",
    modules: "モジュール",
    prerequisites: "前提条件",
    recommendedPrerequisites: "推奨される前提条件",
    completeBeforeStarting: "開始前にこれらのコースを完了してください",
    viewDetails: "詳細を見る",
    description: "説明",
    showMore: "もっと見る",
    showLess: "少なく表示",
    whyChooseThisCourse: "このコースを選ぶ理由",
    expertInstructorsTitle: "専門講師",
    expertInstructorsDesc: "10年以上の経験",
    handsOnLabsTitle: "実践ラボ",
    handsOnLabsDesc: "実世界プロジェクト",
    certificationTitle: "資格取得",
    certificationDesc: "業界認定",
    studentFeedback: "受講生の声",
    showMoreReviews: "もっとレビューを見る",
    faqTitle: "よくある質問",
    courseFee: "受講料",
    free: "無料",
    enrollNow: "今すぐ登録",
    readyToMaster: "{{courseTitle}}をマスターする準備はできましたか？",
    readyToMasterDesc: "このコースを {{rating}}★ と評価した {{count}} 名以上の受講生の仲間入りをしましょう",
    reviews: [
      { user: "アメリア・チェン", date: "2日前", text: "本当に素晴らしいコースです！構成が完璧で、各モジュールが前の内容を基に構築されています。6週間で知識ゼロから自分のアプリケーションを作成できるようになりました。" },
      { user: "ラヴィ・パテル", date: "1週間前", text: "これまで受けた中で最高のコースです。ペースも良く、プロジェクトも素晴らしいです。すでに仕事でこれらのスキルを応用し、昇進しました！" },
      { user: "ソフィア・ロドリゲス", date: "2週間前", text: "本当に包括的なコースです。基礎から高度なトピックまで全てカバーされています。並外れた価値があります。" },
    ],
    faqs: [
      { q: "技術的な要件は何ですか？", a: "インターネット接続のある標準的なノートPCまたはデスクトップPC。全てのツールは無料でオープンソースです。" },
      { q: "修了証はありますか？", a: "はい、LinkedInや履歴書用の確認済み修了証が発行されます。" },
      { q: "プログラミング経験がなくても大丈夫ですか？", a: "このコースは全てのレベル向けに設計されています。基礎から始めて一歩ずつ積み上げていきます。" },
    ]
  },
  ko: {
    loading: "코스 불러오는 중...",
    notFound: "코스를 찾을 수 없습니다",
    home: "홈",
    training: "교육",
    trainingInCity: "{{cityTitle}} 교육",
    ratings: "개의 평점",
    hoursTotal: "총 {{hours}}시간",
    lessons: "레슨",
    maxStudents: "최대 {{count}}명",
    downloadBrochure: "브로셔 다운로드",
    whatYouWillLearn: "학습 내용",
    courseIncludes: "이 코스에 포함된 내용:",
    onDemandVideo: "{{hours}}시간 {{minutes}}분 온디맨드 비디오",
    handsOnExercises: "실습 과제",
    certificateOfCompletion: "수료증",
    fullLifetimeAccess: "평생 무제한 액세스",
    accessOnMobile: "모바일 액세스",
    courseContent: "코스 내용",
    modules: "모듈",
    prerequisites: "선행 조건",
    recommendedPrerequisites: "권장 선행 코스",
    completeBeforeStarting: "시작하기 전에 이 코스들을 완료하세요",
    viewDetails: "상세 보기",
    description: "상세 설명",
    showMore: "더 보기",
    showLess: "간략히 보기",
    whyChooseThisCourse: "이 코스를 선택해야 하는 이유",
    expertInstructorsTitle: "전문가 강사",
    expertInstructorsDesc: "10년 이상의 경력",
    handsOnLabsTitle: "실습 랩",
    handsOnLabsDesc: "실제 프로젝트",
    certificationTitle: "자격증",
    certificationDesc: "업계 공인",
    studentFeedback: "수강생 후기",
    showMoreReviews: "리뷰 더 보기",
    faqTitle: "자주 묻는 질문",
    courseFee: "수강료",
    free: "무료",
    enrollNow: "지금 등록하기",
    readyToMaster: "{{courseTitle}}을 마스터할 준비가 되셨나요?",
    readyToMasterDesc: "이 코스를 {{rating}}★으로 평가한 {{count}}명 이상의 수강생과 함께하세요",
    reviews: [
      { user: "아멜리아 첸", date: "2일 전", text: "정말 환상적인 코스입니다! 구조가 완벽하며 각 모듈이 이전 모듈을 바탕으로 구축됩니다. 6주 만에 지식 제로에서 나만의 애플리케이션을 구축하게 되었습니다." },
      { user: "라비 파텔", date: "1주 전", text: "지금까지 들은 코스 중 최고입니다. 진행 속도도 적당하고 프로젝트도 훌륭합니다. 이미 업무에 이 기술들을 적용하여 승진했습니다!" },
      { user: "소피아 로드리게스", date: "2주 전", text: "정말 포괄적인 코스입니다. 기초부터 고급 주제까지 모든 것을 다룹니다. 가치가 매우 높습니다." },
    ],
    faqs: [
      { q: "기술적 요구 사항은 무엇인가요?", a: "인터넷 연결이 가능한 표준 노트북 또는 데스크탑. 모든 도구는 무료이며 오픈 소스입니다." },
      { q: "수료증이 발급되나요?", a: "네, LinkedIn 및 이력서용 확인된 수료증을 받게 됩니다." },
      { q: "프로그래밍 경험이 없어도 되나요?", a: "이 코스는 모든 수준을 위해 설계되었습니다. 기초부터 시작하여 단계별로 진행합니다." },
    ]
  },
  pt: {
    loading: "Carregando curso...",
    notFound: "Curso não encontrado",
    home: "Início",
    training: "Treinamento",
    trainingInCity: "Treinamento em {{cityTitle}}",
    ratings: "avaliações",
    hoursTotal: "{{hours}}h no total",
    lessons: "lições",
    maxStudents: "Máx {{count}}",
    downloadBrochure: "Baixar Brochura",
    whatYouWillLearn: "O que você aprenderá",
    courseIncludes: "Este curso inclui:",
    onDemandVideo: "{{hours}}h {{minutes}}m de vídeo sob demanda",
    handsOnExercises: "Exercícios práticos",
    certificateOfCompletion: "Certificado de conclusão",
    fullLifetimeAccess: "Acesso vitalício",
    accessOnMobile: "Acesso no celular",
    courseContent: "Conteúdo do curso",
    modules: "módulos",
    prerequisites: "Pré-requisitos",
    recommendedPrerequisites: "Pré-requisitos recomendados",
    completeBeforeStarting: "Conclua estes cursos antes de começar",
    viewDetails: "Ver Detalhes",
    description: "Descrição",
    showMore: "Mostrar mais",
    showLess: "Mostrar menos",
    whyChooseThisCourse: "Por que escolher este curso?",
    expertInstructorsTitle: "Instrutores Especialistas",
    expertInstructorsDesc: "10+ anos de experiência",
    handsOnLabsTitle: "Laboratórios Práticos",
    handsOnLabsDesc: "Projetos reais",
    certificationTitle: "Certificação",
    certificationDesc: "Reconhecida pela indústria",
    studentFeedback: "Feedback dos alunos",
    showMoreReviews: "Mostrar mais avaliações",
    faqTitle: "Perguntas Frequentes",
    courseFee: "Valor do curso",
    free: "Grátis",
    enrollNow: "Inscreva-se Agora",
    readyToMaster: "Pronto para dominar {{courseTitle}}?",
    readyToMasterDesc: "Junte-se a {{count}}+ alunos que avaliaram este curso com {{rating}}★",
    reviews: [
      { user: "Amelia Chen", date: "há 2 dias", text: "Curso absolutamente fantástico! A estrutura é perfeita — cada módulo se baseia no anterior. Passei de zero conhecimento para construir minhas próprias aplicações em 6 semanas." },
      { user: "Ravi Patel", date: "há 1 semana", text: "Melhor curso que já fiz. Bom ritmo, excelentes projetos. Já apliquei essas habilidades no meu trabalho e fui promovido!" },
      { user: "Sofia Rodriguez", date: "há 2 semanas", text: "Curso realmente abrangente. Cobre tudo, desde o básico até tópicos avançados. Valor excepcional." },
    ],
    faqs: [
      { q: "Quais são os requisitos técnicos?", a: "Um laptop ou desktop padrão com conexão à internet. Todas as ferramentas são gratuitas e de código aberto." },
      { q: "Existe certificado?", a: "Sim, você receberá um certificado de conclusão verificado para o LinkedIn e currículo." },
      { q: "E se eu não tiver experiência em programação?", a: "O curso foi projetado para todos os níveis. Começamos do básico e construímos passo a passo." },
    ]
  },
  tr: {
    loading: "Kurs yükleniyor...",
    notFound: "Kurs bulunamadı",
    home: "Anasayfa",
    training: "Eğitim",
    trainingInCity: "{{cityTitle}} konumunda Eğitim",
    ratings: "değerlendirme",
    hoursTotal: "toplam {{hours}} saat",
    lessons: "ders",
    maxStudents: "Maks {{count}}",
    downloadBrochure: "Broşürü İndir",
    whatYouWillLearn: "Neler öğreneceksiniz",
    courseIncludes: "Bu kurs şunları içerir:",
    onDemandVideo: "{{hours}} saat {{minutes}} dakika isteğe bağlı video",
    handsOnExercises: "Uygulamalı egzersizler",
    certificateOfCompletion: "Bitirme sertifikası",
    fullLifetimeAccess: "Ömür boyu tam erişim",
    accessOnMobile: "Mobilden erişim",
    courseContent: "Kurs içeriği",
    modules: "modül",
    prerequisites: "Ön bilgiler",
    recommendedPrerequisites: "Önerilen Ön Koşullar",
    completeBeforeStarting: "Başlamadan önce bu kursları tamamlayın",
    viewDetails: "Detayları Görüntüle",
    description: "Açıklama",
    showMore: "Daha fazla göster",
    showLess: "Daha az göster",
    whyChooseThisCourse: "Neden bu kursu seçmelisiniz?",
    expertInstructorsTitle: "Uzman Eğitmenler",
    expertInstructorsDesc: "10+ yıl deneyim",
    handsOnLabsTitle: "Uygulamalı Laboratuvarlar",
    handsOnLabsDesc: "Gerçek dünya projeleri",
    certificationTitle: "Sertifika",
    certificationDesc: "Sektör tarafından tanınan",
    studentFeedback: "Öğrenci geri bildirimi",
    showMoreReviews: "Daha fazla değerlendirme göster",
    faqTitle: "Sıkça Sorulan Sorular",
    courseFee: "Kurs ücreti",
    free: "Ücretsiz",
    enrollNow: "Şimdi Kaydol",
    readyToMaster: "{{courseTitle}} Konusunda Uzmanlaşmaya Hazır mısınız?",
    readyToMasterDesc: "Bu kursu {{rating}}★ olarak derecelendiren {{count}}+ öğrenciye katılın",
    reviews: [
      { user: "Amelia Chen", date: "2 gün önce", text: "Kesinlikle harika bir kurs! Yapı mükemmel - her modül bir önceki üzerine inşa ediliyor. 6 haftada sıfır bilgiden kendi uygulamalarımı oluşturmaya geçtim." },
      { user: "Ravi Patel", date: "1 hafta önce", text: "Aldığım en iyi kurs. Hız iyi, projeler mükemmel. Bu becerileri zaten işimde uyguladım ve terfi aldım!" },
      { user: "Sofia Rodriguez", date: "2 hafta önce", text: "Gerçekten kapsamlı bir kurs. Temellerden ileri seviye konulara kadar her şeyi kapsıyor. Olağanüstü değer." },
    ],
    faqs: [
      { q: "Teknik gereksinimler nelerdir?", a: "İnternet bağlantısı olan standart bir dizüstü veya masaüstü bilgisayar. Tüm araçlar ücretsiz ve açık kaynaklıdır." },
      { q: "Sertifika var mı?", a: "Evet, LinkedIn ve özgeçmiş için doğrulanmış bir bitirme sertifikası alacaksınız." },
      { q: "Programlama deneyimim yoksa ne olur?", a: "Kurs tüm seviyeler için tasarlanmıştır. Temellerden başlıyoruz ve adım adım ilerliyoruz." },
    ]
  },
  zh: {
    loading: "正在加载课程...",
    notFound: "找不到课程",
    home: "首页",
    training: "培训",
    trainingInCity: "在 {{cityTitle}} 的培训",
    ratings: "条评价",
    hoursTotal: "共 {{hours}} 小时",
    lessons: "节课",
    maxStudents: "最多 {{count}} 人",
    downloadBrochure: "下载手册",
    whatYouWillLearn: "你将学到什么",
    courseIncludes: "本课程包括：",
    onDemandVideo: "{{hours}} 小时 {{minutes}} 分钟点播视频",
    handsOnExercises: "实操练习",
    certificateOfCompletion: "修了证书",
    fullLifetimeAccess: "终生访问权限",
    accessOnMobile: "移动端访问",
    courseContent: "课程内容",
    modules: "个模块",
    prerequisites: "先决条件",
    recommendedPrerequisites: "推荐先修课程",
    completeBeforeStarting: "开始前请完成这些课程",
    viewDetails: "查看详情",
    description: "课程描述",
    showMore: "展开更多",
    showLess: "收起",
    whyChooseThisCourse: "为什么选择这门课程？",
    expertInstructorsTitle: "专家讲师",
    expertInstructorsDesc: "10 年以上经验",
    handsOnLabsTitle: "实操实验室",
    handsOnLabsDesc: "真实世界项目",
    certificationTitle: "认证",
    certificationDesc: "业界认可",
    studentFeedback: "学员反馈",
    showMoreReviews: "查看更多评价",
    faqTitle: "常见问题",
    courseFee: "课程费用",
    free: "免费",
    enrollNow: "立即报名",
    readyToMaster: "准备好精通 {{courseTitle}} 了吗？",
    readyToMasterDesc: "加入将本课程评为 {{rating}}★ 的 {{count}}+ 名学员行列",
    reviews: [
      { user: "Amelia Chen", date: "2 天前", text: "绝对棒极了的课程！结构完美——每个模块都建立在前面的基础之上。我在 6 周内从零基础到了能够构建自己的应用程序。" },
      { user: "Ravi Patel", date: "1 周前", text: "我上过的最好的课程。节奏很好，项目也非常出色。我已经把这些技能应用到了工作中并获得了晋升！" },
      { user: "Sofia Rodriguez", date: "2 周前", text: "非常全面的课程。涵盖了从基础到高级主题的所有内容。物超所值。" },
    ],
    faqs: [
      { q: "技术要求是什么？", a: "一台能够上网的标准笔记本电脑或台式机。所有工具都是免费且开源的。" },
      { q: "有证书吗？", a: "有的，你将获得用于 LinkedIn 和简历的验证修了证书。" },
      { q: "如果没有编程经验怎么办？", a: "课程专为所有水平设计。我们从基础开始，循序渐进地构建知识体系。" },
    ]
  }
};

languages.forEach(lang => {
  const filePath = path.join(__dirname, '..', 'src', 'translations', `${lang}.ts`);
  let content = fs.readFileSync(filePath, 'utf8');

  const dict = translations[lang];
  const dictString = JSON.stringify(dict, null, 2).replace(/"([^"]+)":/g, '$1:');
  
  // Clean up the stringification for TypeScript
  const formattedDict = dictString.split('\n').map(line => '  ' + line).join('\n');

  if (content.includes('coursePage:')) {
    console.log(`coursePage already exists in ${lang}.ts, skipping.`);
    return;
  }

  // Find the last closing brace and insert before it
  const lastBraceIndex = content.lastIndexOf('};');
  if (lastBraceIndex !== -1) {
    const newContent = content.slice(0, lastBraceIndex) + `  coursePage: ${dictString},\n` + content.slice(lastBraceIndex);
    fs.writeFileSync(filePath, newContent);
    console.log(`Localized coursePage for: ${lang}.ts`);
  }
});

console.log('DONE');
